# Generated by Django 2.2.4 on 2020-07-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companycompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='processAsset/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogpost')),
            ],
        ),
    ]
