# Generated by Django 2.2.4 on 2020-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField1',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField2',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField3',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField4',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField5',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField6',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField7',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField8',
            field=models.FloatField(default=-1, max_length=200),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='testField9',
            field=models.FloatField(default=-1, max_length=200),
        ),
    ]
