# Generated by Django 2.2.4 on 2020-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200708_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycompare',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
