# Generated by Django 2.2.4 on 2020-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companycompare_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycompare',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='longdesc',
            field=models.TextField(blank=True),
        ),
    ]
