# Generated by Django 2.2.4 on 2020-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200712_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='compares',
            field=models.ManyToManyField(to='core.companyCompare'),
        ),
    ]
