# Generated by Django 2.2.4 on 2020-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_compares'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycompare',
            name='lat',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companycompare',
            name='long',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='compares',
            field=models.ManyToManyField(blank=True, to='core.companyCompare'),
        ),
    ]
