# Generated by Django 2.2.4 on 2020-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200716_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
