# Generated by Django 2.2.4 on 2020-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
