# Generated by Django 2.2.4 on 2020-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpost_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcpsSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooltype', models.CharField(choices=[('elementarty', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School'), ('special', 'Special Schools')], default='high', max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('ppp_2014_2015', models.FloatField(max_length=200)),
                ('ppp_2018_2019', models.FloatField(max_length=200)),
            ],
        ),
    ]
