# Generated by Django 2.2.4 on 2020-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mcpsschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpsschool',
            name='lat',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='long',
            field=models.FloatField(default=22, max_length=200),
            preserve_default=False,
        ),
    ]
