# Generated by Django 2.2.4 on 2020-07-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200724_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2015_2016',
            field=models.FloatField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2016_2017',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2017_2018',
            field=models.FloatField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
