# Generated by Django 2.2.4 on 2020-08-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zipcode',
            new_name='zipcodeArchive',
        ),
    ]
