# Generated by Django 2.2.4 on 2020-08-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200810_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('geodata', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
