# Generated by Django 2.2.4 on 2020-08-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.CharField(max_length=500),
        ),
    ]
