# Generated by Django 2.2.4 on 2020-08-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200810_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zipcodeArchive',
            new_name='zipcode',
        ),
    ]
