# Generated by Django 2.2.4 on 2020-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200810_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='average_income',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
