# Generated by Django 2.2.4 on 2020-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_zipcode_average_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2014_2015_rank',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2015_2016_rank',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2016_2017_rank',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2017_2018_rank',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcpsschool',
            name='ppp_2018_2019_rank',
            field=models.FloatField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
