# Generated by Django 2.2.4 on 2020-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200810_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
