# Generated by Django 2.2.4 on 2020-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_zipcode_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='population',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
