# Generated by Django 2.2.4 on 2020-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_zipcode_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='density',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
